{
  "rules": {
    "indentation": 2,
    "no-color-keywords": true,
    "no-css-comments": true,
    "no-duplicate-properties": true,
    "no-empty-rulesets": true,
    "no-important": true,
    "no-invalid-hex": true,
    "no-mergeable-selectors": true,
    "no-misspelled-properties": true,
    "no-qualifying-elements": [true, { "allow-element-with-attribute": true }],
    "no-trailing-whitespace": true,
    "no-url-domains": true,
    "no-url-protocols": true,
    "no-vendor-prefixes": [true, { "ignore-non-standard": true }],
    "property-sort-order": "alphabetical",
    "quotes": "single",
    "space-after-colon": 1,
    "space-after-comma": 1,
    "space-before-brace": 1,
    "space-before-colon": 0,
    "trailing-semicolon": true,
    "url-quotes": true
  }
}
