name: Frontend Build

on:
  push:
    paths:
      - "app/static/src/**"
      - "package.json"
      - "package-lock.json"
  pull_request:
    paths:
      - "app/static/src/**"
      - "package.json"
      - "package-lock.json"

jobs:
  build-frontend:
    name: Build Frontend Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint SCSS
        run: npm run lint:scss

      - name: Lint JavaScript
        run: npm run lint:js

      - name: Build assets
        run: npm run build

      - name: Optimize images
        run: npm run optimize:images

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-assets
          path: app/static/dist/
          retention-days: 7

      - name: Analyze bundle size
        run: npm run analyze

      - name: Comment bundle size on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const bundleReport = fs.readFileSync('bundle-report.txt', 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Bundle Size Report\n\n\`\`\`\n${bundleReport}\n\`\`\``
            });
