name: Frontend Build

on:
  push:
    paths:
      - "frontend/src/**"
      - "app/static/src/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.js"
      - "tailwind.config.js"
  pull_request:
    paths:
      - "frontend/src/**"
      - "app/static/src/**"
      - "package.json"
      - "package-lock.json"
      - "vite.config.js"
      - "tailwind.config.js"

jobs:
  build-frontend:
    name: Build Frontend Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint JavaScript
        run: npm run lint:js

      - name: Lint CSS/SCSS
        run: npm run lint:css

      - name: Build Frontend Assets
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-assets
          path: app/static/dist/
          retention-days: 7

      - name: Run E2E Tests
        run: npx playwright test

      - name: Bundle Size Analysis
        run: |
          echo "## Vite Build Report" > bundle-report.txt
          echo "" >> bundle-report.txt
          echo "Build completed successfully with Vite!" >> bundle-report.txt
          echo "" >> bundle-report.txt
          ls -la app/static/dist/ >> bundle-report.txt

      - name: Comment bundle size on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const bundleReport = fs.readFileSync('bundle-report.txt', 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Bundle Size Report\n\n\`\`\`\n${bundleReport}\n\`\`\``
            });
