name: Security Audit

on:
  schedule:
    - cron: "0 2 * * 1" # Run every Monday at 2 AM UTC
  workflow_dispatch:

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit semgrep

      - name: Python dependency security check
        run: |
          safety check -r requirements.txt --json --output safety-report.json || true

      - name: Static security analysis
        run: |
          bandit -r app/ -f json -o bandit-report.json || true

      - name: Semgrep security scan
        run: |
          semgrep --config=auto app/ --json --output=semgrep-report.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            safety-report.json
            bandit-report.json
            semgrep-report.json

      - name: Create security issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Security vulnerabilities found in automated scan',
              body: 'Security scan failed. Please check the workflow logs and security reports.',
              labels: ['security', 'priority-high']
            })
